<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/YOUR_DATABASE
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/database_one
>>>>>>> 984f4764b48fbc07fed2e1177b809cda2717b5df
spring.datasource.username=YOUR_USER
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true