spring.datasource.url=jdbc:postgresql://localhost:5432/database_one
spring.datasource.username=postgres
spring.datasource.password=30052023LaLA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true